### ISSUE TITLE
Why code is blank ?

### ISSUE THREAD

**Issue by niish03** [asaikarthikeya/androidLearning#1]
I can't find **source code** here !

**Comment by niish03** [comment]
Ping me on @niish.03 on instagram , lets solve that issue there

**Comment by asaikarthikeya** [comment]
Please close that issue and PR in enviro-car before mentor closes it

**Comment by niish03** [comment]
> Please close that issue and PR in enviro-car before mentor closes it

Why ? I haven't copied any code and i have worked constantly 2 hours to do this.

**Comment by niish03** [comment]
Can we just discuss this @niish.03 instagram

**Comment by asaikarthikeya** [comment]
please donot solve any issue that i opened in envirocar, I am working on them.
